### ISSUE TITLE
Configure ```DC01``` and ```DC02``` for redundant ADDS & DNS services.

### ISSUE THREAD

**Issue by morganconnors** [SYS-265-Final/SYS-265-Final#2]
Update the wiki for [DC01](https://github.com/SYS-265-Final/SYS-265-Final/wiki/DC01) and [DC02](https://github.com/SYS-265-Final/SYS-265-Final/wiki/DC02)

**Comment by morganconnors** [comment]
Initially needed to add DC02 to domain.

**Comment by Isaiah-River** [comment]
Resolved
